### ISSUE TITLE
NoMethodError: undefined method `liked_by' for #<Enumerator:0x00000004a72138>

### ISSUE THREAD

**Issue by andrewcase** [ryanto/acts_as_votable#11]
I'm probably just doing something completely stupid as I'm a rails newb, but I followed to the best of my knowledge the documentation and get "NoMethodError: undefined method `liked_by' for #Enumerator:0x00000004a72138" error.

Added acts_as_votable to Gemfile
Ran: bundle install; rails generate acts_as_votable:migration; rake db:migrate
I've added "acts_as_voter" to my User model.
I've added "acts_as_votable" to my Post model.
All without any problems, but then when I try to do votes, it doesn't work:

```
1.9.3p194 :002 > @posts = Post.all
  Post Load (13.5ms)  SELECT "posts".* FROM "posts" 
 => [#<Post id: 1, ...>] 

1.9.3p194 :003 > @users = User.all
  User Load (5.7ms)  SELECT "users".* FROM "users" 
 => [#<User id: 1, ...>] 

1.9.3p194 :004 > @post = @posts.find(1)
 => #<Enumerator: [#<Post id: 1, ...>]:find(1)> 

1.9.3p194 :005 > @user = @users.find(1)
 => #<Enumerator: [#<User id: 1, ...>]:find(1)> 

1.9.3p194 :006 > @post.liked_by @user
NoMethodError: undefined method `liked_by' for #<Enumerator:0x00000004a72138>
    from (irb):6
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands/console.rb:47:in `start'
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands/console.rb:8:in `start'
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'

1.9.3p194 :007 > @user.likes @post
NoMethodError: undefined method `likes' for #<Enumerator:0x000000055846c0>
    from (irb):7
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands/console.rb:47:in `start'
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands/console.rb:8:in `start'
    from /home/acase/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.5/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Any ideas?

**Comment by dizo1** [comment]
Hallo ? how do i restrict voting to 24 hours per user
